// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUeM78DQ_yN6sfDY_0XlXoTV--bZR23HY',
    appId: '1:519672171004:web:2550215a3a5bed25d7ca79',
    messagingSenderId: '519672171004',
    projectId: 'adsb-support-desk',
    authDomain: 'adsb-support-desk.firebaseapp.com',
    storageBucket: 'adsb-support-desk.firebasestorage.app',
    measurementId: 'G-TKL5KWLFW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwImJHImHzyO2YpYpcmFmt_eWnXEpnzbQ',
    appId: '1:519672171004:android:656ed888338909fdd7ca79',
    messagingSenderId: '519672171004',
    projectId: 'adsb-support-desk',
    storageBucket: 'adsb-support-desk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZP50bI5am1RxeBSzhPGGGkQXmmUHY2-A',
    appId: '1:519672171004:ios:c46835b3fb44257ed7ca79',
    messagingSenderId: '519672171004',
    projectId: 'adsb-support-desk',
    storageBucket: 'adsb-support-desk.firebasestorage.app',
    iosBundleId: 'com.example.adsbSupportDesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZP50bI5am1RxeBSzhPGGGkQXmmUHY2-A',
    appId: '1:519672171004:ios:c46835b3fb44257ed7ca79',
    messagingSenderId: '519672171004',
    projectId: 'adsb-support-desk',
    storageBucket: 'adsb-support-desk.firebasestorage.app',
    iosBundleId: 'com.example.adsbSupportDesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUeM78DQ_yN6sfDY_0XlXoTV--bZR23HY',
    appId: '1:519672171004:web:b18f135e113bfd28d7ca79',
    messagingSenderId: '519672171004',
    projectId: 'adsb-support-desk',
    authDomain: 'adsb-support-desk.firebaseapp.com',
    storageBucket: 'adsb-support-desk.firebasestorage.app',
    measurementId: 'G-SKTQDQGG4C',
  );
}
